version: "3.8"

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    image: ceddit-server
    container_name: ceddit-node-server
    command: /usr/src/app/node_modules/.bin/nodemon app.js
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    env_file: ./.env
    environment:
      - NODE_ENV=development
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    volumes:
      - data-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ceddit
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123
    ports:
      - "3307:3306"
    networks:
      - app-network

  prisma:
    image: prismagraphql/prisma:1.8.2
    restart: always
    volumes:
      - ./:/usr/src/app
    environment:
      PRISMA_DATABASE_URL: mysql://admin:123@mysql:3306/ceddit
      PRISMA_GENERATE: 'true'
    ports:
      - "5555:5555"
    depends_on:
      - mysql
    networks:
      - app-network


  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: ceddit-client
    container_name: ceddit-react-client
    command: npm start
    volumes:
      - ./client/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  data-volume:
  node_modules:
  web-root:
    driver: local


